language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
    - ".cache/Cypress"
script:
  - yarn test
  - yarn test:coverage
  - yarn build
  - yarn cy:ci:test
deploy:
  provider: script
  script: npx deploy-to-gh-pages --repo yuriMalakhov/kiko ./build
  on:
    branch: master