language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
    - ".cache/Cypress"
script:
  - npm test
  - npm run test:coverage
  - npm run build
  - npm run cy:ci:test
  - npm run deploy