language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
    - ".cache/Cypress"
script:
  - npm test
  - npm run test:coverage
  - npm run cy:ci:test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
